apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: standalone
bases:
  - ../resources
patchesStrategicMerge:
- service.yaml
configMapGenerator:
- name: alpha-features
  literals:    
  - ENABLE_ALPHA="false"