steps:
- id: skaffold-run
  name: "gcr.io/k8s-skaffold/skaffold:v1.23.0"
  entrypoint: "/bin/bash"
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials lab --zone us-central1-a --project PROJECT_ID
      skaffold run -p prod
  env:
    - 'CLOUDSDK_COMPUTE_REGION=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=lab'
    - 'GCLOUD_PROJECT=PROJECT_ID'
