apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
  - image: gcr.io/PROJECT_ID/gke-standalone-app
    buildpacks:
      builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kustomize:
    paths: 
      - config
portForward:
  - resourceType: service
    resourceName: gke-standalone-app
    namespace: default
    port: 80
    localPort: 8080
profiles:
  - name: remote-build
    build:
      googleCloudBuild: {}
  - name: prod
    deploy:
      kustomize:
        paths:
        - kubernetes-manifests/gke-standalone-app/overlays